const cat = {
  oralCare: "oralCare",
  babyCare: "babyCare",
  beverages: "beverages",
  cleaningDisinfectant: "cleaning & disinfectant",
  hairCare: "hairCare",
  homeCare: "homeCare",
  kitchen: "kitchen",
  personalCare: "personalCare",
  skinCare: "skinCare",
  stationary: "stationary",
};
export const categories = [
  {
    _id: 1001,
    name: "Oral Care",
    image: "https://i.ibb.co/kM0FR2h/cat-Tv-Audio.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "oralCare",
  },
  {
    _id: 1002,
    name: "Baby Care",
    image: "https://i.ibb.co/71hR65V/catTvBox.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "babyCare",
  },
  {
    _id: 1003,
    name: "Beverages",
    image: "https://i.ibb.co/0V0g6Gz/cat-Powertool.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "beverages",
  },
  {
    _id: 1004,
    name: "Cleaning & Disinfectant",
    image: "https://i.ibb.co/zST2Xdp/cat-Headphone.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "cleaningDisinfectant",
  },
  {
    _id: 1005,
    name: "Hair Care",
    image: "https://i.ibb.co/jgk59BL/catPhone.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "hairCare",
  },
  {
    _id: 1006,
    name: "Home Care",
    image: "https://i.ibb.co/B4NKfBZ/cat-Smart-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "homeCare",
  },

  {
    _id: 1008,
    name: "Personal Care",
    image: "https://i.ibb.co/xjpdQrr/cat-Robot-Clean.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "personalCare",
  },
  {
    _id: 1009,
    name: "Skin Care",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "skinCare",
  },
  {
    _id: 1010,
    name: "Stationary",
    image: "https://i.ibb.co/qCzTx4F/cat-Tablet.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "stationary",
  },

  {
    _id: 1013,
    name: "Kitchen & Food",
    image: "https://i.ibb.co/Kj8wXMz/food-category.jpg",
    description: "Delicious food items including fried rice, noodles, and various meat dishes.",
    _base: "kitchen",
    isKitchenPage: true,
  },
];

export const highlightsProducts = [
  {
    _id: 3001,
    name: "Pet Supplies",
    title: "food, treats, toys, and more",
    buttonTitle: "Shop now",
    image: "https://i.ibb.co/S73fs9fm/petbanner.webp",
    _base: "/product",
    color: "#000000",
  },
  {
    _id: 3002,
    name: "Baby Care",
    title: "Get baby care essentials in minutes",
    buttonTitle: "Shop now",
    image: "https://i.ibb.co/TD7MTBgm/61489237316811-Y3-Jvc-Cw0-MDUs-Mz-E3-LDAs-MA.jpg",
    _base: "/category/babyCare",
    color: "#000000",
  },
  {
    _id: 3003,
    name: "Pharmacy at your doorstep",
    title: "cough syrup, pain relief sprays, and more",
    buttonTitle: "Shop Now",
    image: "https://i.ibb.co/0pMWpgkM/pharmacy-banner.jpg",
    _base: "/product",
    color: "#000000",
  },
];

export const blogsData = [
  // {
  //   _id: 4001,
  //   image: "https://i.ibb.co/XbQf5HS/blogOne.webp",
  //   title: "iPhone 15 rear camera design will be available",
  //   _base: "Technology",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  // },
  // {
  //   _id: 4002,
  //   image: "https://i.ibb.co/wzNpcwp/blogTwo.webp",
  //   title: "Setup your surround sound speaker",
  //   _base: "Samrt thing",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  // },
  // {
  //   _id: 4003,
  //   image: "https://i.ibb.co/prdZ3s8/blog-Three.webp",
  //   title: "Hook up a receiver for your home theater",
  //   _base: "Life style",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  // },
];

export const products = [
  // --- CSV IMPORTED PRODUCTS START ---
  {
    _id: 2100,
    name: "Lizol - Citrus",
    images: ["https://griepit.in/wp-content/uploads/2025/03/61W8NHxqS8L._SX679_.jpg"],
    description: "Lizol - Citrus cleaning liquid.",
    regularPrice: 116,
    discountedPrice: 116,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Cleaning & Disinfectants",
    brand: "Lizol",
    isStock: true,
    isNew: true,
    overView: "Cleaning Liquid",
    _base: cat?.cleaningDisinfectant,
    pageType: "cleaning"
  },
  {
    _id: 2101,
    name: "Lizol Disinfectant Surface Cleaner - Floral",
    images: ["https://i.ibb.co/Fq3LHjk7/Lizol-Disinfectant-Surface-Cleaner-Floral.jpg"],
    description: "Lizol Disinfectant Surface Cleaner - Floral.",
    regularPrice: 116,
    discountedPrice: 116,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Cleaning & Disinfectants",
    brand: "Lizol",
    isStock: true,
    isNew: true,
    overView: "Surface Cleaner",
    _base: cat?.cleaningDisinfectant,
    pageType: "cleaning"
  },
  {
    _id: 2102,
    name: "Harpic",
    images: ["https://i.ibb.co/27PkMcLL/Harpic.jpg"],
    description: "Harpic toilet cleaner.",
    regularPrice: 44,
    discountedPrice: 44,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Cleaning & Disinfectants",
    brand: "Harpic",
    isStock: true,
    isNew: true,
    overView: "Toilet Cleaner",
    _base: cat?.cleaningDisinfectant,
    pageType: "cleaning"
  },
  {
    _id: 2103,
    name: "Robin - Fabric Whiteness",
    images: ["https://i.ibb.co/kVJJk5wB/Robin-Fabric-Whiteness.jpg"],
    description: "Robin - Fabric Whiteness for laundry.",
    regularPrice: 39,
    discountedPrice: 39,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Cleaning & Disinfectants",
    brand: "Robin",
    isStock: true,
    isNew: true,
    overView: "Laundry",
    _base: cat?.cleaningDisinfectant,
    pageType: "cleaning"
  },
  {
    _id: 2104,
    name: "Patanjali Super Dishwash Bar",
    images: ["https://i.ibb.co/PGgV1zK3/Patanjali-Super-Dishwash-Bar.webp"],
    description: "Patanjali Super Dishwash Bar for utensils.",
    regularPrice: 10,
    discountedPrice: 10,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Cleaning & Disinfectants",
    brand: "Patanjali",
    isStock: true,
    isNew: true,
    overView: "Dishwash Bar",
    _base: cat?.cleaningDisinfectant,
    pageType: "cleaning"
  },
  {
    _id: 2105,
    name: "Odopic Dishwash Bar",
    images: ["https://i.ibb.co/WvSt4cjj/Odopic-Dishwash-Bar.webp"],
    description: "Odopic Dishwash Bar for utensils.",
    regularPrice: 60,
    discountedPrice: 60,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Cleaning & Disinfectants",
    brand: "Odopic",
    isStock: true,
    isNew: true,
    overView: "Dishwash Bar",
    _base: cat?.cleaningDisinfectant,
    pageType: "cleaning"
  },
  {
    _id: 2106,
    name: "Tide Washing Powder - Jasmine & Rose",
    images: ["https://i.ibb.co/RTygC3B4/Tide-Washing-Powder-Jasmine-Rose.webp"],
    description: "Tide Washing Powder - Jasmine & Rose fragrance.",
    regularPrice: 10,
    discountedPrice: 10,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Cleaning & Disinfectants",
    brand: "Tide",
    isStock: true,
    isNew: true,
    overView: "Washing Powder",
    _base: cat?.cleaningDisinfectant,
    pageType: "cleaning"
  },
  // --- CSV IMPORTED PRODUCTS END ---
  {
    _id: 2107,
    name: "Dettol Liquid Hand Wash",
    images: ["https://i.ibb.co/pjZ62sjw/Dettol-Liquid-Hand-Wash.webp"],
    description: "Dettol Liquid Hand Wash for hygiene.",
    regularPrice: 99,
    discountedPrice: 99,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Cleaning & Disinfectants",
    brand: "Dettol",
    isStock: true,
    isNew: true,
    overView: "Hand Wash",
    _base: cat?.cleaningDisinfectant,
    pageType: "cleaning"
  },
  {
    _id: 2108,
    name: "Dettol Sensitive Liquid Hand Wash Refiller",
    images: ["https://i.ibb.co/1GtCkqR7/Dettol-Sensitive-Liquid-Hand-Wash-Refiller.webp"],
    description: "Dettol Sensitive Liquid Hand Wash Refiller.",
    regularPrice: 50,
    discountedPrice: 50,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Cleaning & Disinfectants",
    brand: "Dettol",
    isStock: true,
    isNew: true,
    overView: "Hand Wash Refiller",
    _base: cat?.cleaningDisinfectant,
    pageType: "cleaning"
  },
  {
    _id: 2109,
    name: "Colin Glass Cleaner",
    images: ["https://i.ibb.co/JwPy559f/Colin-Glass-Cleaner.webp"],
    description: "Colin Glass Cleaner for shiny surfaces.",
    regularPrice: 109,
    discountedPrice: 109,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Cleaning & Disinfectants",
    brand: "Colin",
    isStock: true,
    isNew: true,
    overView: "Glass Cleaner",
    _base: cat?.cleaningDisinfectant,
    pageType: "cleaning"
  },
  {
    _id: 2110,
    name: "Vivel Soap - Lime and Aloe Vera",
    images: ["https://i.ibb.co/TDTR8X2c/Vivel-Soap-Lime-and-Aloe-Vera.jpg"],
    description: "Vivel Soap with Lime and Aloe Vera.",
    regularPrice: 40,
    discountedPrice: 40,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Personal Care",
    brand: "Vivel",
    isStock: true,
    isNew: true,
    overView: "Soap",
    _base: cat?.personalCare,
    pageType: "personalCare"
  },
  {
    _id: 2111,
    name: "Vivel Soap - Lotus Oil + Aloe Vera",
    images: ["https://i.ibb.co/zTwc9Ym2/Vivel-Soap-Lotus-Oil-Aloe-Vera.webp"],
    description: "Vivel Soap with Lotus Oil and Aloe Vera.",
    regularPrice: 40,
    discountedPrice: 40,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Personal Care",
    brand: "Vivel",
    isStock: true,
    isNew: true,
    overView: "Soap",
    _base: cat?.personalCare,
    pageType: "personalCare"
  },
  {
    _id: 2112,
    name: "Lux Soap - Radiant Glow Rose",
    images: ["https://i.ibb.co/BVrZ2cG3/Lux-Soap-Radiant-Glow-Rose.jpg"],
    description: "Lux Soap with Radiant Glow Rose fragrance.",
    regularPrice: 100,
    discountedPrice: 100,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Personal Care",
    brand: "Lux",
    isStock: true,
    isNew: true,
    overView: "Soap",
    _base: cat?.personalCare,
    pageType: "personalCare"
  },
  {
    _id: 2113,
    name: "Dettol Soap - Original",
    images: ["https://griepit.in/wp-content/uploads/2025/03/DettolOriginalSoap.jpg"],
    description: "Dettol Soap - Original for germ protection.",
    regularPrice: 10,
    discountedPrice: 10,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Personal Care",
    brand: "Dettol",
    isStock: true,
    isNew: true,
    overView: "Soap",
    _base: cat?.personalCare,
    pageType: "personalCare"
  },
  {
    _id: 2114,
    name: "Dove Soap - Cream Bar",
    images: ["https://griepit.in/wp-content/uploads/2025/03/71aBGCWpnuL._AC_SL1500_.jpg"],
    description: "Dove Soap - Cream Bar for smooth skin.",
    regularPrice: 61,
    discountedPrice: 61,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Personal Care",
    brand: "Dove",
    isStock: true,
    isNew: true,
    overView: "Soap",
    _base: cat?.personalCare,
    pageType: "personalCare"
  },
  {
    _id: 2115,
    name: "Godrej Cinthol Soap - Intense Deo Fragrance",
    images: ["https://i.ibb.co/6Rg3xLrF/Godrej-Cinthol-Soap-Intense-Deo-Fragrance.webp"],
    description: "Godrej Cinthol Soap with Intense Deo Fragrance.",
    regularPrice: 10,
    discountedPrice: 10,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Personal Care",
    brand: "Godrej",
    isStock: true,
    isNew: true,
    overView: "Soap",
    _base: cat?.personalCare,
    pageType: "personalCare"
  },
  {
    _id: 2116,
    name: "Godrej Cinthol Soap - Cool",
    images: ["https://griepit.in/wp-content/uploads/2025/03/1-100-cool-soap-cinthol-original-imaffnk4h9gjhrvz.jpeg"],
    description: "Godrej Cinthol Soap - Cool.",
    regularPrice: 10,
    discountedPrice: 10,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Personal Care",
    brand: "Godrej",
    isStock: true,
    isNew: true,
    overView: "Soap",
    _base: cat?.personalCare,
    pageType: "personalCare"
  },
  {
    _id: 2117,
    name: "Pears Soap - Pure and Gentle",
    images: ["https://i.ibb.co/yTxk2g5/Pears-Soap-Pure-and-Gentle.webp"],
    description: "Pears Soap - Pure and Gentle.",
    regularPrice: 54,
    discountedPrice: 54,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Personal Care",
    brand: "Pears",
    isStock: true,
    isNew: true,
    overView: "Soap",
    _base: cat?.personalCare,
    pageType: "personalCare"
  },
  {
    _id: 2118,
    name: "Lifebuoy Soap - Expert Defence",
    images: ["https://i.ibb.co/wZh5gP6H/Lifebuoy-Soap-Expert-Defence.webp"],
    description: "Lifebuoy Soap - Expert Defence.",
    regularPrice: 112,
    discountedPrice: 112,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Personal Care",
    brand: "Lifebuoy",
    isStock: true,
    isNew: true,
    overView: "Soap",
    _base: cat?.personalCare,
    pageType: "personalCare"
  },
  {
    _id: 2119,
    name: "Dabur Amla Hair Oil",
    images: ["https://griepit.in/wp-content/uploads/2025/04/Dabur-Amla-Hair-Oil.jpg"],
    description: "Dabur Amla Hair Oil for strong hair.",
    regularPrice: 20,
    discountedPrice: 20,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Dabur",
    isStock: true,
    isNew: true,
    overView: "Hair Oil",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2120,
    name: "Streax Hair Serum - Walnut Oil",
    images: ["https://i.ibb.co/KcKRQ704/Streax-Hair-Serum-Walnut-Oil.webp"],
    description: "Streax Hair Serum with Walnut Oil.",
    regularPrice: 130,
    discountedPrice: 130,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Streax",
    isStock: true,
    isNew: true,
    overView: "Hair Serum",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2121,
    name: "Livon Hair Serum - Anti-Frizz",
    images: ["https://i.ibb.co/k2kcZTDq/Livon-Hair-Serum-Anti-Frizz.jpg"],
    description: "Livon Hair Serum - Anti-Frizz.",
    regularPrice: 279,
    discountedPrice: 279,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Livon",
    isStock: true,
    isNew: true,
    overView: "Hair Serum",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2122,
    name: "Pantene Conditioner - Hairfall Control",
    images: ["https://i.ibb.co/nN77K6k8/Pantene-Conditioner-Hairfall-Control.webp"],
    description: "Pantene Conditioner for Hairfall Control.",
    regularPrice: 229,
    discountedPrice: 229,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Pantene",
    isStock: true,
    isNew: true,
    overView: "Conditioner",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2123,
    name: "Pantene Shampoo - Silky Smooth",
    images: ["https://griepit.in/wp-content/uploads/2025/03/41dZ9dF-LlL.jpg"],
    description: "Pantene Shampoo for silky smooth hair.",
    regularPrice: 205,
    discountedPrice: 205,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Pantene",
    isStock: true,
    isNew: true,
    overView: "Shampoo",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2124,
    name: "Dove Shampoo - Anti Dandruff Solutions",
    images: ["https://i.ibb.co/ks9P5pCZ/Dove-Shampoo-Anti-Dandruff-Solutions.jpg"],
    description: "Dove Shampoo - Anti Dandruff Solutions.",
    regularPrice: 205,
    discountedPrice: 205,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Dove",
    isStock: true,
    isNew: true,
    overView: "Shampoo",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2125,
    name: "Dove Shampoo - Hair Fall Rescue",
    images: ["https://i.ibb.co/WNpPWbNd/Dove-Shampoo-Hair-Fall-Rescue.jpg"],
    description: "Dove Shampoo - Hair Fall Rescue.",
    regularPrice: 205,
    discountedPrice: 205,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Dove",
    isStock: true,
    isNew: true,
    overView: "Shampoo",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2126,
    name: "Dove Shampoo - Daily Shine",
    images: ["https://i.ibb.co/LhCJvWYm/Dove-Shampoo-Daily-Shine.jpg"],
    description: "Dove Shampoo - Daily Shine.",
    regularPrice: 205,
    discountedPrice: 205,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Dove",
    isStock: true,
    isNew: true,
    overView: "Shampoo",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2127,
    name: "Head & Shoulders Shampoo - Smooth & Silky",
    images: ["https://i.ibb.co/gLwpkSQn/Head-Shoulders-Shampoo-Smooth-Silky.jpg"],
    description: "Head & Shoulders Shampoo - Smooth & Silky.",
    regularPrice: 205,
    discountedPrice: 205,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Head & Shoulders",
    isStock: true,
    isNew: true,
    overView: "Shampoo",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  // --- FULLY AUTOMATED CSV IMPORT CONTINUED ---
  {
    _id: 2128,
    name: "Head & Shoulders Shampoo - Silky Black",
    images: ["https://i.ibb.co/wZh5gP6H/Lifebuoy-Soap-Expert-Defence.webp"],
    description: "Head & Shoulders Shampoo - Silky Black.",
    regularPrice: 84,
    discountedPrice: 84,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Head & Shoulders",
    isStock: true,
    isNew: true,
    overView: "Shampoo",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2129,
    name: "Head & Shoulders Shampoo - Neem",
    images: ["https://i.ibb.co/fdmRGspb/Head-Shoulders-Shampoo-Neem.jpg"],
    description: "Head & Shoulders Shampoo - Neem.",
    regularPrice: 105,
    discountedPrice: 105,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Head & Shoulders",
    isStock: true,
    isNew: true,
    overView: "Shampoo",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2130,
    name: "Head & Shoulders Shampoo - Anti-Hairfall",
    images: ["https://i.ibb.co/7dhbyjQH/Head-Shoulders-Shampoo-Anti-Hairfall.jpg"],
    description: "Head & Shoulders Shampoo - Anti-Hairfall.",
    regularPrice: 84,
    discountedPrice: 84,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Head & Shoulders",
    isStock: true,
    isNew: true,
    overView: "Shampoo",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2131,
    name: "Sunsilk Shampoo - Stunning Black Shine",
    images: ["https://i.ibb.co/tMFVqC7w/Sunsilk-Shampoo-Stunning-Black-Shine.jpg"],
    description: "Sunsilk Shampoo - Stunning Black Shine.",
    regularPrice: 164,
    discountedPrice: 164,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "Hair Care",
    brand: "Sunsilk",
    isStock: true,
    isNew: true,
    overView: "Shampoo",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  {
    _id: 2132,
    name: "Tresemme Shampoo - Lamellar Gloss",
    images:["https://i.ibb.co/vycQnkd/Tresemme-Shampoo-Lamellar-Gloss.webp"],
    description: "Tresemme Shampoo Lamellar Gloss for shiny, smooth hair.",
    regularPrice: 220,
    discountedPrice: 199,
    quantity: 1,
    rating: 4.6,
    reviews: 0,
    category: "Hair Care",
    brand: "Tresemme",
    isStock: true,
    isNew: true,
    overView: "Shampoo",
    _base: cat?.hairCare,
    pageType: "hairCare"
  },
  // ...repeat for all remaining products from products.csv
  // --- END FULLY AUTOMATED CSV IMPORT ---

  {
    _id: 2026,
    name: "Pork Fried Rice",
    images: [
      "https://i.ibb.co/PsQbvfyY/Pork-Fried-Rice.jpg",
      
    ],
    description: "Delicious pork fried rice made with fresh ingredients and authentic spices.",
    regularPrice: 190,
    discountedPrice: 190,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Fried Rice",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2027,
    name: "Chicken Fried Rice",
    images: [
      "https://i.ibb.co/NgZY3hw6/Chicken-Fried-Rice.png"
    ],
    description: "Classic chicken fried rice prepared with tender chicken pieces and fresh vegetables.",
    regularPrice: 180,
    discountedPrice: 180,
    quantity: 1,
    rating: 4.5,
    reviews: 45,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Fried Rice",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2028,
    name: "Mix Fried Rice",
    images: [
      "https://i.ibb.co/1kMwc0G/Mix-Fried-Rice.webp"
    ],
    description: "Special mix fried rice with a combination of different meats and vegetables.",
    regularPrice: 210,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.6,
    reviews: 55,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Fried Rice",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2029,
    name: "Veg Fried Rice",
    images: [
      "https://i.ibb.co/B5TBwmnH/Veg-Fried-Rice.jpg"
    ],
    description: "Healthy vegetarian fried rice loaded with fresh vegetables and aromatic spices.",
    regularPrice: 170,
    discountedPrice: 170,
    quantity: 1,
    rating: 4.4,
    reviews: 40,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Fried Rice",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2030,
    name: "Pork Chow",
    images: [
      "https://i.ibb.co/rKD1BVJR/Pork-Chow.jpg"
    ],
    description: "Savory pork chow noodles with tender meat and fresh vegetables.",
    regularPrice: 190,
    discountedPrice: 190,
    quantity: 1,
    rating: 4.5,
    reviews: 48,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Noodles",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2031,
    name: "Chicken Chow",
    images: [
      "https://i.ibb.co/7d92XCHY/Chicken-Chow.jpg"
    ],
    description: "Classic chicken chow noodles with succulent chicken pieces.",
    regularPrice: 180,
    discountedPrice: 180,
    quantity: 1,
    rating: 4.5,
    reviews: 42,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Noodles",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2032,
    name: "Mix Chow",
    images: [
      "https://i.ibb.co/zhmpWVHp/Mix-Chow.jpg"
    ],
    description: "Special mix chow noodles with assorted meats and vegetables.",
    regularPrice: 210,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.6,
    reviews: 52,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Noodles",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2033,
    name: "Veg Chow",
    images: [
      "https://i.ibb.co/yL84y5s/Veg-Chow.jpg"
    ],
    description: "Healthy vegetarian chow noodles with fresh vegetables.",
    regularPrice: 170,
    discountedPrice: 170,
    quantity: 1,
    rating: 4.4,
    reviews: 38,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Noodles",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2034,
    name: "Pork Chilli",
    images: [
      "https://i.ibb.co/gLhsLMtf/Pork-Chilli.jpg"
    ],
    description: "Spicy pork chilly prepared with tender meat and special sauce.",
    regularPrice: 260,
    discountedPrice: 260,
    quantity: 1,
    rating: 4.7,
    reviews: 58,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Pork Dishes",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2035,
    name: "Pork Bhujia",
    images: [
      "https://i.ibb.co/SXtCWq3T/Pork-Bhujia.jpg"
    ],
    description: "Traditional pork bhujia cooked with authentic spices.",
    regularPrice: 200,
    discountedPrice: 200,
    quantity: 1,
    rating: 4.5,
    reviews: 45,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Pork Dishes",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2036,
    name: "Pork Ribs",
    images: [
      "https://i.ibb.co/wrFj30bf/Pork-Ribs.jpg"
    ],
    description: "Succulent pork ribs grilled to perfection with special marinade.",
    regularPrice: 420,
    discountedPrice: 420,
    quantity: 1,
    rating: 4.8,
    reviews: 65,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Pork Dishes",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2037,
    name: "Crispy Pork Belly",
    images: [
      "https://i.ibb.co/NnFbzx7h/Pork-Belly-Recipe-sq.jpg"
    ],
    description: "Perfectly crispy pork belly with tender meat inside.",
    regularPrice: 400,
    discountedPrice: 400,
    quantity: 1,
    rating: 4.8,
    reviews: 70,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Pork Dishes",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2038,
    name: "Chicken Chilli",
    images: [
      "https://i.ibb.co/60YQMn2x/Chicken-Chilli.jpg"
    ],
    description: "Spicy chicken chilly made with tender chicken pieces and special sauce.",
    regularPrice: 210,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.6,
    reviews: 55,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Chicken Dishes",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2039,
    name: "Chicken Wings Hot/Spicy",
    images: [
      "https://i.ibb.co/4RP2zgNs/Chicken-Wings.jpg"
      
    ],
    description: "Crispy and spicy chicken wings with special hot sauce.",
    regularPrice: 220,
    discountedPrice: 220,
    quantity: 1,
    rating: 4.7,
    reviews: 62,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Chicken Dishes",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  {
    _id: 2040,
    name: "Chicken Gizzard Dry/Fry/Gravy",
    images: [
      "https://i.ibb.co/s9s1BnLx/Chicken-Gizzard.jpg"
    ],
    description: "Flavorful chicken gizzard prepared in your choice of style - dry, fried, or with gravy.",
    options: ["Dry", "Fry", "Gravy"],
    regularPrice: 250,
    discountedPrice: 250,
    quantity: 1,
    rating: 4.5,
    reviews: 48,
    category: "Kitchen & Food",
    brand: "Kitchen Specials",
    isStock: true,
    overView: "Chicken Dishes",
    isNew: true,
    _base: cat?.kitchen,
    isKitchenOnly: true,
    pageType: "kitchen"
  },
  
];